# Generated by Django 3.0.8 on 2020-07-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('ifsc', models.CharField(max_length=11)),
                ('micr_code', models.CharField(max_length=9)),
                ('branch', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
