# Generated by Django 3.0.8 on 2020-07-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifscfinder', '0003_auto_20200702_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='contact',
        ),
    ]
