# Generated by Django 3.0.8 on 2020-07-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifscfinder', '0005_auto_20200702_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
