# Generated by Django 3.0.8 on 2020-07-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifscfinder', '0006_bank_bank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='district',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='ifsc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='state',
            field=models.TextField(),
        ),
    ]
