# Generated by Django 3.0.8 on 2020-07-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifscfinder', '0007_auto_20200702_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='city',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
