# Generated by Django 3.0.8 on 2020-07-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifscfinder', '0008_bank_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='city',
        ),
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bank',
            name='district',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bank',
            name='ifsc',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='bank',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
